# Generated by Django 2.0.13 on 2020-02-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_ciudadm_estado_civilm_estadom_generom_ocupacionm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudadm',
            old_name='nombre',
            new_name='ciudad',
        ),
    ]
