# Generated by Django 2.0.13 on 2020-02-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20200213_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='example3',
            name='estado_civil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Profile.Estado_civilM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example3',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.CiudadM'),
        ),
        migrations.AlterField(
            model_name='example3',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.EstadoM'),
        ),
        migrations.AlterField(
            model_name='example3',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.GeneroM'),
        ),
        migrations.AlterField(
            model_name='example3',
            name='ocupacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.OcupacionM'),
        ),
    ]
